name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Either development or production'

env:
  GOOGLE_APPLICATION_CREDENTIALS: 'admin-sdk.json'

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
      - uses: ruby/setup-ruby@v1

      - name: Retrieve the secret and decode it to a file
        env:
          ADMIN_SDK_BASE64: ${{ secrets.FIREBASE_ADMIN_BASE_64_ENCODED_JSON }}
        run: |
          echo $ADMIN_SDK_BASE64 | base64 --decode > admin-sdk.json

      - name: Bundle install
        run: bundle install

      - name: install dependencies
        run: yarn install

      - name: install functions dependencies
        run: yarn installFirebaseFunctions

      - name: Set Firebase Project
        run: yarn firebase use ${{ inputs.ENV }}

      - name: Deploy Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '../admin-sdk.json'
        run: yarn deployFirebaseFunctions

  deploy-firestore-rules:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
      - uses: ruby/setup-ruby@v1

      - name: Retrieve the secret and decode it to a file
        env:
          ADMIN_SDK_BASE64: ${{ secrets.FIREBASE_ADMIN_BASE_64_ENCODED_JSON }}
        run: |
          echo $ADMIN_SDK_BASE64 | base64 --decode > admin-sdk.json

      - name: Bundle install
        run: bundle install

      - name: install dependencies
        run: yarn install

      - name: install functions dependencies
        run: yarn installFirebaseFunctions

      - name: Set Firebase Project
        run: yarn firebase use ${{ inputs.ENV }}

      - name: Deploy Functions
        run: yarn deployFirestoreRules

  deploy-storage-rules:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
      - uses: ruby/setup-ruby@v1

      - name: Retrieve the secret and decode it to a file
        env:
          ADMIN_SDK_BASE64: ${{ secrets.FIREBASE_ADMIN_BASE_64_ENCODED_JSON }}
        run: |
          echo $ADMIN_SDK_BASE64 | base64 --decode > admin-sdk.json

      - name: Bundle install
        run: bundle install

      - name: install dependencies
        run: yarn install

      - name: install functions dependencies
        run: yarn installFirebaseFunctions

      - name: Set Firebase Project
        run: yarn firebase use ${{ inputs.ENV }}

      - name: Deploy Functions
        run: yarn deployStorageRules
