name: development

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  deploy:
    needs: tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'development'
    secrets: inherit
  distribute-apps:
    needs: tests
    uses: ./.github/workflows/distribute-apps.yml
    with:
      environment: 'development'
    secrets: inherit
