name: develop

on:
  push:
    branches:
      - develop
      - feature/9-functions-deploy

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  deploy:
    environment: development
    needs: tests
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
  distribute-apps:
    needs: tests
    uses: ./.github/workflows/distribute-apps.yml
