name: develop

on:
  push:
    branches:
      - develop

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  deploy:
    needs: tests
    uses: ./.github/workflows/deploy.yml
    with:
      ENV: 'development'
    secrets: inherit
  distribute-apps:
    needs: tests
    uses: ./.github/workflows/distribute-apps.yml
