name: production

on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: choice
        options:
          - app
          - functions
          - all
        default: 'all'
      version_string:
        required: true
        type: string

jobs:
  # check_branch:
  #   runs-on: ubuntu-latest
  # steps:
  #   - name: Check branch
  #     if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
  #     run: |
  #       echo "ERROR: You can only run this on main branches"
  #
  tests:
    uses: ./.github/workflows/test.yml
  get_version_number:
    runs-on: ubuntu-latest
    outputs:
      version_string: ${{ steps.get-latest-release.outputs.release }}
      previous_tag: ${{ steps.get-previous-release.outputs }}
    steps:
      - uses: pozetroninc/github-action-get-latest-release@master
        id: get-latest-release
        with:
          repository: ${{ github.repository }}
      - name: Echo Version
        run: |
          echo "${{ steps.get-latest-release.outputs.release }}"
      - name: Verify Release Created
        if: steps.get-latest-release.outputs.release != inputs.version_string
        run: |
          echo "ERROR: Your version string must match the latest published release in github"
          exit 1
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version_string}}
      - id: get-previous-release
        run: git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`

  prepare_for_release:
    needs: [tests, get_version_number]
    runs-on: macos-14
    environment: 'production'
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY_PRIVATE_SSH }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: yarn
      - uses: ruby/setup-ruby@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - name: Bundle install
        run: bundle install
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: Retrieve the secret and decode it to a file
        env:
          ADMIN_SDK_BASE64: ${{ secrets.FIREBASE_ADMIN_BASE_64_ENCODED_JSON }}
          GOOGLE_PLAY_KEY_JSON_BASE64_ENCODED: ${{ secrets.GOOGLE_PLAY_KEY_JSON_BASE64_ENCODED }}
          ANDROID_RELEASE_KEYSTORE_BASE64_ENCODED: ${{ secrets.ANDROID_RELEASE_KEYSTORE_BASE64_ENCODED }}
          ANDROID_RELEASE_KEYSTORE_PROPERTIES_BASE64_ENCODED: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PROPERTIES_BASE64_ENCODED }}
          ANDROID_PROD_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_PROD_KEYSTORE_PASSWORD }}
        run: |
          echo $ADMIN_SDK_BASE64 | base64 --decode > admin-sdk.json
          mkdir android/app/play_store_keys
          echo $GOOGLE_PLAY_KEY_JSON_BASE64_ENCODED | base64 --decode > android/app/play_store_keys/murray-apps-9ae8e17f9aa5.json
          echo $ANDROID_RELEASE_KEYSTORE_PROPERTIES_BASE64_ENCODED | base64 --decode > android/app/play_store_keys/release_keystore.properties
          echo $ANDROID_RELEASE_KEYSTORE_BASE64_ENCODED | base64 --decode > android/app/release.keystore
          touch .env.${{ inputs.environment }}
          echo REACT_APP_FIREBASE_AUTH_WEB_CLIENT_ID = "${{ vars.MURRAY_APPS_DEV_REACT_APP_FIREBASE_AUTH_WEB_CLIENT_ID }}" >> .env.${{ inputs.environment }}
          echo REACT_APP_FIREBASE_FUNCTIONS_BASE_URL = "${{ vars.MURRAY_APPS_DEV_REACT_APP_FIREBASE_FUNCTIONS_BASE_URL }}" >> .env.${{ inputs.environment }}
          echo REMOTE_CONFIG_FETCH_DEBUG = "false" >> .env.${{ inputs.environment }}
          cat .env.${{ inputs.environment }}
      - name: Prepare For Release
        if: ${{ inputs.release_type == 'app' || inputs.release_type == 'all' }}
        run: bundle exec fastlane prepare_for_release version_number_string:${{ inputs.version_string }} release_type:${{ inputs.release_type }}
  deploy:
    needs: [tests, get_version_number, prepare_for_release]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'production'
      version_string: '${{ needs.get_version_number.outputs.version_string }}'
      previous_tag: '${{ needs.get_version_number.outputs.previous_tag }}'
    secrets: inherit
    if: ${{ inputs.release_type == 'functions' || inputs.release_type == 'all' }}
  distribute-apps:
    needs: [tests, get_version_number, prepare_for_release]
    uses: ./.github/workflows/distribute-apps.yml
    with:
      environment: 'production'
      version_string: '${{ needs.get_version_number.outputs.version_string }}'
    secrets: inherit
    if: ${{ inputs.release_type == 'app' || inputs.release_type == 'all' }}
