name: pull-request

on:
  pull_request:
    branches:
      - develop

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  deploy:
    on: workflow_dispatch
    needs: tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'development'
    secrets: inherit
  distribute-apps:
    on: workflow_dispatch
    needs: tests
    uses: ./.github/workflows/distribute-apps.yml
    with:
      environment: 'development'
    secrets: inherit
