name: release

on:
  push:
    branches:
      - release

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/release'
        run: |
          echo "ERROR: You can only run this on release branches"
          exit 1
  tests:
    uses: ./.github/workflows/test.yml
  distribute-apps:
    runs-on: ubuntu-latest
    needs: [tests, check_branch]
    steps:
      - uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
      - uses: ./.github/workflows/distribute-apps.yml
        with:
          environment: 'production'
        secrets: inherit
    if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/release'
