name: test

on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: install functions dependencies
        run: cd functions && yarn install --frozen-lockfile

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: test firebase functions
        run: yarn test-functions
